:PROPERTIES:
:ID:       0f387c73-ec41-4d83-98ce-cd677644889f
:END:

#+FILETAGS: @awkravchuk

#+title: OnDemandTutorial

Когда разработчик начинает исследовать какой-то инструмент у него возникают типичные вопросы вроде "Как с помощью этого я могу сделать то-то".

Можно предугадыть их. И делать "отвечающие на вопрос" туториалы, вроде:
- Как нарисовать квадрат
- Как обрабатывать события (напр. клики мышкой)
- Как сделать детекцию столновений в игре

Туториалы кратки (10 мин) для прохождения, и чем больше пройдено - тем больше уверенности. Что-то неизвестное теперь выглядит как достижимая цель - нужно всего только пройти еще один туториал. И ты уже вовлечен в проект.

Такие заметки легко связать в [[https://en.wikipedia.org/wiki/Directed_acyclic_graph][DAG]] что отвечает на вопрос "опережающих ссылок" (что еще я должен изучить прежде чем понять это)

Обоснование:

Изучение чего-то большого выглядит как неподьемная задача, а сам процесс нуждается в постоянном подкреплении каждого шага.

Кроме того это полезно и для документирования - слабосвязанный DAG проще перестраивать, чем классический учебный план.
