:PROPERTIES:
:ID:       4e6afb5a-ee34-4fb6-b001-e1ba002dbfc6
:END:
#+title: Medley

https://interlisp.org/docs/2021-Medley-Interlisp-Annual-Report.pdf

http://notecards.online/notecards/user-guide

Годовой отчет Medley Interlisp за 2021 год
15 ноября 2021 г.

* Вступление

«Возродить» что-то - значит снова оживить. Сделать Medley Interlisp снова живым означает привести систему в порядок, чтобы другие, не имеющие ранее глубокого опыта работы с Interlisp, могли использовать и оценить его (хотя бы как виртуальный антиквариат).

Проект Medley Interlisp по-настоящему стартовал в марте 2020 года (в начале пандемии). Этот отчет посвящен деятельности и достижениям после виртуальной встречи LispNYC в декабре 2020 г. (запись по адресу: https://www.youtube.com/watch?v=x6-b_hazcyk).

В этом документе работа над проектом разбита на три основные категории:
- Работа над самой программой - отладка, адаптация и т. Д.
- Документация к программному обеспечению.
- Создание организации и развитие сообщества.

Программное обеспечение «Программная археология» - это процесс, подобный сборке функциональной чаши из черепков глиняной посуды.

Мы не выполнили задачу, но у нас есть стабильная база.

Программное обеспечение старое: оно было разработано в период между 70-ми и 90-ми годами, со многими изменениями, многими разными людьми, работающими с небольшим количеством внутренней документации. Было много «экскурсий» в поддержку систем или опций, которые больше не доступны. За последние 25 лет стандарты программного обеспечения развивались для C, Common Lisp, кодов символов и операционных систем.

* Майко

Maiko - это реализация виртуальной машины Medley Interlisp на языке C. Его можно найти на https://github.com/interlisp/maiko.

- Соответствие: мы заставляем Maiko соответствовать ожиданиям современных компиляторов C. Удаление поддержки устаревших систем упростило задачу.
- SDL: в настоящее время осуществляется поддержка SDL, многоплатформенного (Windows, Mac OS X, Linux, iOS и Android) графического инструментария в качестве замены X11. SDL можно использовать вместо X11 в качестве прокладки для собственной оконной системы, которая (мы надеемся) позволит системе работать в Windows без отдельной установки X11, Docker Desktop или WSL2.
Благодаря работе по очистке код стал намного более переносимым, чем когда-либо прежде. Системы, которые мы тестировали или регулярно строим на предмет включения
- Операционные системы: macOS, Linux, FreeBSD, Solaris 11.4.
- Архитектуры ЦП: i386, x86_64, arm7, aarch64, SPARC-32 и -64
Это касается Raspberry Pi (linux.arm7) и Windows 10 (с WSL2 или Docker). и Windows 11 (включая WSL2). Производительность выдающаяся. Raspberry Pi за 40 долларов выполняет задачи Lisp в 250-1000 раз быстрее, чем Dorado (высокопроизводительная машина Xerox 1132 Lisp за 90 тыс. Долларов).


* Medley

Остальная часть системы реализована на Лиспе: интерпретаторы Interlisp и Common Lisp, компиляторы, инструменты отладки, редакторы, оконная система, графика, драйверы устройств. В прошлом году:
- Организация: мы очищали и систематизировали, сравнивали даты в файлах и решали, какие из них оставить; сценарии обслуживания сборки и утилиты Lisp.
- EOL и преобразование символов: код для обработки кодов конца строки и символов был обобщен на пути к полной поддержке Unicode. (См. Выпуск Medley # 2)
- Интеграция с Git: файловый менеджер Interlisp был разработан для версионных файлов с номерами версий. GitHub имеет другую графическую модель истории. Мы создали «restore-версии» для восстановления пронумерованных версий из журналов git, но проблемы глубже. Если будет поддерживаться стиль программирования Interlisp, мы должны решить эти проблемы. (см. выпуски Medley # 265, # 226)
- Нагрузки: мы воссоздали метод построения системы с нуля, который раньше занимал многочасовый ручной процесс.
- Отладка: мы нашли и исправили множество ошибок: несколько проблем 2000 года, некоторые случаи «битовой гнили» и битых файлов, неполные реализации и исправление кода на «неправильном уровне».
- Модернизация: управление окном путем перетаскивания строки заголовка и выбора угла, прокрутка колесика мыши, буфер обмена - это, по-видимому, необходимые улучшения для современных пользователей.
- Процесс выпуска и автоматизация: GitHub Actions теперь используются для автоматизации процесса сборки выпусков Medley, а также контейнера Docker, развернутого в Docker Hub как Interlisp / Medley. Это дает возможность запускать Medley в облаке (в Amazon Web Services, Azure, Google Cloud) или на рабочем столе Windows с удаленным доступом в браузере.
Приложения Interlisp
Одна из причин восстановления Medley Interlisp - поддержка восстановления приложений, написанных для него.
- Notecards: Notecards - это гипертекстовая система, разработанная задолго до Интернета или Apple Hypercard. http://notecards.online был создан с помощью выпуска Medley / Docker, который запускал Medley «в облаке» с доступом через веб-браузер. Мы применяем это, чтобы работать на других
Системы Medley Interlisp и другие для создания.
- Rooms: Rooms - это менеджер рабочего стола Lisp для менее загроможденного доступа к окнам с интересными нововведениями. В репозитории Medley. Нагрузки, но непроверенные.
- CLOS: объектная система Common Lisp добавляет стиль структур классов Common Lisp, добавленный после реализации Common Lisp Medley в стандарт ANSI. Также загружает но непроверенно.
LOOPS: объектно-ориентированное дополнение Lisp (к Interlisp) до CLOS. Интересен тем, что на его основе созданы приложения ИИ, в том числе «Truckin» - демонстрация «программирования знаний [см. Статью]. Исходный код приложения Truckin существует и будет
используется для тестирования LOOPS после полной загрузки и компиляции.
- LFG: the Grammar Writer’s Workbench,
- LispUsers: программное обеспечение, создаваемое пользователями (до того, как «открытый исходный код» был в моде). Мы проверили более половины файлов LispUsers.

* Books

- Interlisp: The Language and Its Usage, by Steve Kaisler, originally published by John
Wiley & Sons, scanned and converted to a compact PDF. This book describes the core
features of the Interlisp language. Now at
https://interlisp.org/docs/1986-Interlisp-language-book-1.pdf.
- Medley Interlisp: The Interactive Programming Environment, by Steve Kaisler,
describes the Interlisp-D Interactive Programming Environment as implemented on
Xerox D-machines and now running on several modern platforms. Now at
https://interlisp.org/docs/2021-interlisp-book-2.pdf.
- Medley Interlisp: Tools and Utilities, by Steve Kaisler (undergoing editing) describes
the editors and tools to be used for program development. It is expected to be completed
and uploaded to Interlisp.org in early December 2021.

Программная документация

Мы преобразовали исходные документы TEdit в PDF (см. Medley-pdfs: https://drive.google.com/drive/folders/1dYPlooXlQSBva9fiDB_XxHH0bDz8F5CU). У нас есть IRM (Справочное руководство Interlisp) со ссылками на интерактивную справку (DInfo), руководства пользователя, примечания к выпуску, учебник. Нам все еще нужно преобразовать и опубликовать документацию для некоторых приложений Interlisp, а также организовать и обновить, чтобы облегчить работу новичкам.

Библиография

Zotero - это библиографическая служба в Интернете. Мы создали Interlisp Zotero материалов, связанных с Lisp, многие элементы с исходным материалом представлены в виде PDF-файлов. Наша цель - иметь исчерпывающий источник информации о связанных с Interlisp технических документах, технических отчетах и ​​руководствах для различных версий и реализаций Interlisp (и, для сравнения) современных конкурентов «Lisp Machine».

Рабочие более старые версии

Помимо современного Medley, мы начали организовывать другие эмуляции старых версий и репозиторий «истории», включая файлы из Interlisp-10, эмулятора «DarkStar» оборудования Xerox 1108/8010 и системных программ для множества различных выпусков. Интерлисп-Д. Мы работаем над созданием более ранней версии Medley (работающей на эмулированном DosBox); в настоящее время доступны с инструкциями в репозитории Interlisp / DOS.

Информационно-пропагандистская деятельность

Чтобы привлечь пользователей и сторонников, нам нужно сделать проект известным.
- Мы разработали и установили на GitHub «Кодекс поведения», «Руководство для участников» и шаблоны задач (хотя мы не использовали шаблоны и должны их просмотреть).
- Поддерживаются дополнительные веб-ресурсы.
  - Веб-сайт https://interlisp.org и его библиография от Zotero.
  - README и другие документы из репозитория
  - Interlisp / medley Wiki (https://github.com/interlisp/medley/wiki).
- Мы отслеживаем упоминания «интерлиспа» в социальных сетях (и разместим ссылку на этот документ).
  - Twitter (@ interlisp8)
  - LinkedIn
  - Reddit
  - Facebook: выпускники Xerox Workstation, группы LISPER.
  - IRC #Interlisp на Libera.chat
  - Группы Meetup и Lisp:
    - LispNYC https://www.meetup.com/LispNYC/,
    - Bay Area Lisp: online-lisp-meets@common-lisp.net
- Конференции, о которых нужно объявить?
  - Европейский симпозиум по Лисп (european-lisp-symposium.org) https://www.european-lisp-symposium.org/
- Музей истории компьютеров (CHM) - мы надеемся предоставить доступ к Interlisp через аналогичный Smalltalk Zoo в CHM (https://computerhistory.org/blog/introducing-the-smalltalk-zoo-48-years-of-smalltalk-history-at-chm/) сетап.
Сеть сохранения программного обеспечения (SPN) https://www.softwarepreservationnetwork.org/ | Повышение сохранности программного обеспечения посредством коллективных действий через их инфраструктуру эмуляции как услуги (https://www.softwarepreservationnetwork.org/emulation-as-a-service-infrastructure/) - это возможный способ сделать доступ к Medley доступным для исследователей.

* Кто мы?

В этом документе мы используем «мы» для обозначения наших участников:
- как участники списка / группы рассылки lispcore@googlegroups.com (ядро Medley Interlisp Google Groups - https://groups.google.com/g/lispcore)
- как участники еженедельного зум-звонка
  - Встречи записываются, но не публично
  - Повестка дня: https://github.com/Interlisp/medley/wiki/Meeting-Agendas-and-Notes
- как члены организации GitHub Interlisp https://github.com/orgs/Interlisp/people
- как участники проекта с открытым исходным кодом
- 384 номера, 133 закрытых, 151 открытых https://github.com/Interlisp/medley/issues. 54 обсуждения https://github.com/Interlisp/medley/discussions
- 191 пулреквест Medley https://github.com/Interlisp/medley/pulls, 387 пул реквестов Maiko https://github.com/Interlisp/maiko/pulls
- как (некоммерческая) корпорация: InterlispORG Inc. https://github.com/Interlisp/medley/wiki/InterlispOrg-Inc
Мы зависим от волонтеров. Если вы хотите помочь, но не знаете, как это сделать, спросите.

* Будущие мероприятия

Здесь перечислены некоторые задачи / проекты; которые были перемещены на GitHub https://github.com/Interlisp/medley/issues/566#issue-1053084010


Благодарности
Мы уже много сделали, но предстоит еще немало. Спасибо Эйбу, Александру, Аруну, Биллу, Блейку, Фрэнку, Хербу, Джону Си, Ларри, Мишель, Нику, Полу, Питеру, Рону, Уэйну, Зои. Момент памяти прошлых участников, включая Джона Сибальского, Уоррена Тейтельмана, Дэнни Bobrow
