:PROPERTIES:
:ID:       0f387c73-ec41-4d83-98ce-cd677644889f
:END:
#+title: OnDemandTutorial

Когда разработчик начинает исследовать какой-то инструмент у него возникают типичные вопросы вроде "Как с помощью этого я могу сделать то-то".

Мы должны предугадывать их. Тогда мы сможем сделать набор туториалов вроде:
- Как с помощью этой графической библиотеки нарисовать квадрат (выводить графические примитивы)
- Как обрабатывать события (напр. клики мышкой) попадающие в область
- Как сделать детекцию столновений

Каждый из этих простых туториалов кажется коротким (10 мин) для прохождения, а их общее количество способствует возрастанию уверенности.

И через некоторое время изучающему кажется что он вполне уверенно обращается с возможностями: может то, это и вот это. Когда вдруг оказывается что он чего-то не может - это выглядит как вызов и как вполне достижимая цель - нужно всего только пройти еще один туториал. И он уже вовлечен в проект.

Мы также можем связать такие туториал в DAG чтобы отслеживать, какие предварительные туториалы должен пройти неофит чтобы понять этот.
